---
- name: this playbook installs httpd
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum:
      name: httpd
      state: installed
    notify: start the service

  handlers:
  - name: start the service
    service:
      name: httpd
      state: started
