---
- name: Setup Tomact
  hosts: all
  become: true
  tasks:
  - name: Install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Java in Ubuntu
    apt:
      name: default-jdk  #because java pkg is not available in Ubuntu
      state: present
    when: ansible_os_family == "Debian"

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.71/bin/apache-tomcat-8.5.71.tar.gz
      dest: /opt

  - name: Untaz the apache pkg
    unarchive:
      src: /opt/apache-tomcat-8.5.71.tar.gz
      dest: /opt
      remote_src: yes

  - name: Add execution permission on startup.sh file
    file: 
      path: /opt/apache-tomcat-8.5.71/bin/startup.sh
      mode: 0777
  - name: start tomcat services
    shell: nohup ./startup.sh
    args: 
      chdir: /opt/apache-tomcat-8.5.71/bin

