---
# handlers file for steup-apache
  - name: start apache service
    service:
      name: httpd
      state: started

  - name: start apache2
    service:
      name: apache
      state: started

  - name: restart apache
    service:
      name: httpd
      state: restarted

  - name: restart apache2
    service:
      name: apache2
      state: restarted
